version: '2.1'

executors:
  # TODO: we currently have python as a build dependency; it is accidentally included in circleci/node
  linux-node-v10:
    docker:
      - image: circleci/node:10
  macos:
    macos:
      xcode: 12.5.0

orbs:
  node: circleci/node@4.5.0

jobs:
  build-test:
    parameters:
      executor:
        type: executor
      install-node:
        type: boolean
        default: false
      # defaults are the same as circleci/node orb:
      install-node-lts:
        type: boolean
        default: false
      install-node-version:
        type: string
        default: "node"
      install-npm-version:
        type: string
        default: "latest"
    executor: << parameters.executor >>
    environment:
      BS_TRAVIS_CI: 1
      NINJA_FORCE_REBUILD: 1
      OCAMLRUNPARAM: "b"
    steps:
      - restore_cache: # try to restore .git folder from cache to speed up checkout
          keys:
            - source-v4-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - source-v4-{{ arch }}-{{ .Branch }}-
            - source-v4-{{ arch }}
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - save_cache: # write .git folder to cache
          key: source-v4-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      # install node and npm for executors where they are not preinstalled
      - when:
          condition: << parameters.install-node >>
          steps:
            - node/install:
                lts: << parameters.install-node-lts >>
                node-version: << parameters.install-node-version >>
                npm-version: << parameters.install-npm-version >>
      - run: node --version
      - run: npm --version

      - node/install-packages # npm ci
      - run: npm test

workflows:
  version: 2
  build-test-all: # workflow name
    jobs:
      - build-test:
          name: linux-node-v10
          executor: linux-node-v10
      - build-test:
          name: macos-node-v10
          executor: macos
          install-node: true
          install-node-version: "10.24.1"
          install-npm-version: "6.14.12"
